### PR TITLE
Quattroporte changes

### LINKED ISSUE #31: [Question] Clarification of PM_INDEX
Hi 
currently discovering your great API.
In my case I get no data on `get_power_data` and found out using pmIndex = 1 works.
I have a Quattroporte.
At least I can explain the pvi data error "NOT_AVAILABLE" (made a pull request)... that is because a Quattroporte can't do anything on the DC side .... so no PV stuff.
Not sure if this should be directly catched at the API for a Quattroporte. Maybe not 🤔 
But The PV generated electricity is measured after converted to AC. And this data is what I get in PM_INDEX 1.

But I'm not sure if changing the pmIndex in general for Quattroporte would be the right way.
I have the feeling the available index numbers are highly dependent on the specific system installation.
And could even be multiple indexes at the same time ?!

I bet somehow the available devices can somehow be discovered. But to prove that we need some tests on different installations. 

For example I found ```EMS_REQ_EXT_SRC_AVAILABLE``` which returned:
```('EMS_EXT_SRC_AVAILABLE', 'Char8', 1)```
Regarding the description in the official Excel, it doesn't sound like to be the PM_INDEX (even it matched in my case). I'm more into that this is kind of "boolean" value. Or maybe (think of the PM_INDEX are somehow hard coded for specific devices) this would return 1 for the device at index 1. But this is just guessing.

At least this is a way to find something out about the specific installation.
Still exploring a bit all the available tags and data... but wanted to ask what you think about this.

PS: pull request for correcting the serialnumber prefix for Quattroporte is in work :D

### PR DESCRIPTION
**Pull request by spali**
suggested solution for Quattroporte 
Fixes #31

### CODE REVIEW

**Comment by fsantini** [comment]
You should try to see if you can get the same information also through ajax, so we can keep the outObj consistent. Maybe you can see what `poll_ajax_raw()` returns?

**Comment by spali** [comment]
@fsantini 
To keep everything together, here the answer for #31 

At least in my case (which I don't know if it is the standard case) it makes more sense in "source" but then as you wrote, I have to "- add" it in the outObj to be consistent.
That would work for my case.
But I'm not sure if this would match any other case.
I can imagine two theories:

-  It could be that they just installed the converter counter the wrong way. But somehow fixed that with a firmware setting to be counted positiv as a source in the GUI. Because there it is shown as "External Power" with a positive value, that counts also positive in the home balance in the GUI. Also it matches the "home" balance I get from the RSCP call that you commented out.

- Or we can assume "External Power" is a power consuming device by design, which then would make sense to have it "minus" in consumption instead of calc it "positive" and add it to "production".

I will post the results for the ajax and the rscp poll call and also the raw ajax result.
Just have to wait till daytime with some production to make it easier to identify the correct ajax values.

By the way, power_data and the new power_data_ext does not work for the web connection. The reason is the _set_serial is called before the initialization of the pmIndex with None. Maybe this has also an impact on other functions I didn't test. But will move the initialization of all these vars to before the _set_serial. Then it works.

**Comment by spali** [comment]
@fsantini 
Here the results of all the different polls and its values.
for debugging, added in the rscp_poll the house in both ways, one is calced as in the current code and the other one is directly from the commented rscp call.
It seems to be hardcoded in E3DC that the additional PM is minus but added positive in the house calculation internally.

The question is should we show it positive or negativ in the api result for "add".

```json
{
  "rscp_poll": {
    "autarky": 98.96,
    "consumption": {
      "battery": 957,
      "house_calc": 577,
      "house_rscp": 577,
      "wallbox": 0
    },
    "production": { "solar": 0, "add": -1536, "grid": -2 },
    "selfConsumption": 99.15,
    "stateOfCharge": 24,
    "sysStatus": 695,
    "time": "2020-11-11 13:19:43.000317+00:00"
  },
  "ajax_poll": {
    "time": "2020-11-11 13:19:17+00:00",
    "sysStatus": "695",
    "stateOfCharge": 24,
    "production": { "solar": 0, "add": -1576, "grid": -9 },
    "consumption": { "battery": 972, "house": 595, "wallbox": 0 }
  },
  "ajax_poll_raw": {
    "TSMS": "<redacted>",
    "POWER_BAT": "972",
    "POWER_LM_L1": "-85",
    "POWER_LM_L2": "-364",
    "POWER_LM_L3": "440",
    "POWER_WALLBOX": "0",
    "serialno": "6<redacted>",
    "time": "2020-11-11 13:19:17",
    "IP": "<redacted>",
    "dataVersion": "1",
    "offlineLevel": "0",
    "SYSSTATUS": "695",
    "POWER_BAT_1": "324",
    "POWER_BAT_2": "324",
    "POWER_BAT_3": "324",
    "POWER_PV_S1": "0",
    "POWER_PV_S2": "0",
    "POWER_PV_S3": "0",
    "POWER_AC_L1": "-335",
    "POWER_AC_L2": "-346",
    "POWER_AC_L3": "-346",
    "POWER_ROOTLM_L1": "-85",
    "POWER_ROOTLM_L2": "-364",
    "POWER_ROOTLM_L3": "440",
    "POWER_C_L1": "401",
    "POWER_C_L2": "80",
    "POWER_C_L3": "114",
    "SOC": "24",
    "PM_ALIVE": "3",
    "PM1_L1": "-803",
    "PM1_L2": "-772",
    "PM1_L3": "-1",
    "PM2_L1": "0",
    "PM2_L2": "0",
    "PM2_L3": "0",
    "PM3_L1": "0",
    "PM3_L2": "0",
    "PM3_L3": "0",
    "PM4_L1": "0",
    "PM4_L2": "0",
    "PM4_L3": "0",
    "WB_ALIVE": "0",
    "WB0_L1": "0",
    "WB0_L2": "0",
    "WB0_L3": "0",
    "WB0PV_L1": "0",
    "WB0PV_L2": "0",
    "WB0PV_L3": "0",
    "WB1_L1": "0",
    "WB1_L2": "0",
    "WB1_L3": "0",
    "WB1PV_L1": "0",
    "WB1PV_L2": "0",
    "WB1PV_L3": "0",
    "WB2_L1": "0",
    "WB2_L2": "0",
    "WB2_L3": "0",
    "WB2PV_L1": "0",
    "WB2PV_L2": "0",
    "WB2PV_L3": "0",
    "WB3_L1": "0",
    "WB3_L2": "0",
    "WB3_L3": "0",
    "WB3PV_L1": "0",
    "WB3PV_L2": "0",
    "WB3PV_L3": "0",
    "WB4_L1": "0",
    "WB4_L2": "0",
    "WB4_L3": "0",
    "WB4PV_L1": "0",
    "WB4PV_L2": "0",
    "WB4PV_L3": "0",
    "WB5_L1": "0",
    "WB5_L2": "0",
    "WB5_L3": "0",
    "WB5PV_L1": "0",
    "WB5PV_L2": "0",
    "WB5PV_L3": "0",
    "WB6_L1": "0",
    "WB6_L2": "0",
    "WB6_L3": "0",
    "WB6PV_L1": "0",
    "WB6PV_L2": "0",
    "WB6PV_L3": "0",
    "PM7_L1": "0",
    "PM7_L2": "0",
    "PM7_L3": "0",
    "LM_COUNT": "3"
  }
}
```

**Comment by spali** [comment]
current state of changes is the same as before ("add" under "production" negative value) and added the web part.

So now you can decide if you want it positive in production or negative in consumption or as it is in the current pull request negative in production.

I would prefer the first one as it is the most intuitive for me.
All variants have the risk, that it may not work for someone else...

**Comment by fsantini** [comment]
> for debugging, added in the rscp_poll the house in both ways, one is calced as in the current code and the other one is directly from the commented rscp call.

So you mean that the house value from RSCP is the same as the calculation that forces it to 0? The calculation was needed because when I first created the library, this result was very different. If they finally fixed it, we can avoid the calculation altogether.

For the rest, I would say that it makes sense to have the additional source reported as following:
```
            'production': {
                'solar' : solar,
                'add' : -add,
                'grid' : grid
            },
```
It's not a big deal, we just need to keep the signs consistent, that means sum(production) - sum(consumption) = 0. This sign choice allows this.

**Comment by spali** [comment]
@fsantini 

ok, will add "add" to production as positive value as in your example. 

About the calculation... I thought maybe you did it because the requests for the values are serial, so not from one point in time. Which can lead to the potential gaps you mentioned. Maybe it wasn't a bug, just timing problem. But in my tests I never had a difference from the rscp value to the calculated one.

Let me know if I should change it back to the rscp provided value or if you want to stick with the calculation.

**Comment by fsantini** [comment]
Great! I tested it on my system too, and the result is indeed correct. Would you please change the code then to use `EMS_REQ_POWER_HOME` instead of the balance calculation? I'll then merge the PR.
I can assure you that it was not like that when I first implemented it :)

**Comment by spali** [comment]
will do it tomorrow asap.

**Comment by spali** [comment]
RSCP: 
```json
{
    "autarky": 99.89,
    "consumption": {
        "battery": 3180,
        "house": 4786,
        "wallbox": 0
    },
    "production": {
        "add": 7982,
        "grid": -16,
        "solar": 0
    },
    "selfConsumption": 99.74,
    "stateOfCharge": 32,
    "sysStatus": 695,
    "time": "2020-11-12T10:11:31.000579+00:00"
}
```
Web:
```json
{
    "consumption": {
        "battery": 3258,
        "house": 4981,
        "wallbox": 0
    },
    "production": {
        "add": 7998,
        "grid": 241,
        "solar": 0
    },
    "stateOfCharge": 32,
    "sysStatus": "695",
    "time": "2020-11-12T10:12:38+00:00"
}
```

**Comment by fsantini** [comment]
Great! Thank you for your contribution!

**Pull request merged**
