### PR TITLE
Update _e3dc.py

### PR DESCRIPTION
**Pull request by t11z**
adapted to changed power meter index

helpmed me to fix issue #64

### CODE REVIEW

**Comment by fsantini** [comment]
Is this affecting all models? Aren't we breaking anything with this change? @vchrisb ?

**Comment by vchrisb** [comment]
`pmIndexExt` is only used once in `poll_ajax` https://github.com/fsantini/python-e3dc/blob/master/e3dc/_e3dc.py#L318
This comment did mention the same issue: https://github.com/fsantini/python-e3dc/issues/43#issuecomment-1093348617

I'll give it a try.

**Comment by vchrisb** [comment]
Without the change it also does break for me, while the change does allow to poll using web connection.
@fsantini can you give it a try with your system to see if it is a general change or only for S10 Mini?

**Review by vchrisb — APPROVED** [review]
LGTM, testes with S10 Mini

**Comment by fsantini** [comment]
Tested on my system too. Confirmed.

**Pull request merged**
